name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to cPanel
        uses: ilooser/cpanel-git-deploy-action@1.1
        with:
          cpanel_host: ${{ secrets.FTP_SERVER }}
          cpanel_username: ${{ secrets.FTP_USERNAME }}
          cpanel_password: ${{ secrets.FTP_PASSWORD }}
          repository: OK-Ro/smartHomes.ug
