on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
    
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.smarthomesug.com
          username: smarthome@smarthomesug.com
          password: ${{ secrets.FTP_PASSWORD }}
